//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6407
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobilus.SmartDevice {
    
    
    public partial class VenteEmbarqueCacheClientSyncProvider : Microsoft.Synchronization.Data.SqlServerCe.SqlCeClientSyncProvider {
        
        public VenteEmbarqueCacheClientSyncProvider() {
            this.ConnectionString = ("Data Source=" 
                        + (System.IO.Path.Combine(System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().GetName().CodeBase), "Inventaire.sdf") + ";Max Database Size=2047"));
        }
        
        public VenteEmbarqueCacheClientSyncProvider(string connectionString) {
            this.ConnectionString = connectionString;
        }
    }
    
    public partial class VenteEmbarqueCacheSyncAgent : Microsoft.Synchronization.SyncAgent {
        
        private XpoAgentTerrainSyncTable _xpoAgentTerrainSyncTable;
        
        private XpoCategorySyncTable _xpoCategorySyncTable;
        
        private XpoClientSyncTable _xpoClientSyncTable;
        
        private XpoMarqueSyncTable _xpoMarqueSyncTable;
        
        private XpoOrderSyncTable _xpoOrderSyncTable;
        
        private XpoOrderLineSyncTable _xpoOrderLineSyncTable;
        
        private XpoProductSyncTable _xpoProductSyncTable;
        
        private XpoProductLineSyncTable _xpoProductLineSyncTable;
        
        private XpoSectorSyncTable _xpoSectorSyncTable;
        
        private XpoStockSyncTable _xpoStockSyncTable;
        
        partial void OnInitialized();
        
        public VenteEmbarqueCacheSyncAgent() {
            this.InitializeSyncProviders();
            this.InitializeSyncTables();
            this.OnInitialized();
        }
        
        public VenteEmbarqueCacheSyncAgent(object remoteSyncProviderProxy) {
            this.InitializeSyncProviders();
            this.InitializeSyncTables();
            this.RemoteProvider = new Microsoft.Synchronization.Data.ServerSyncProviderProxy(remoteSyncProviderProxy);
            this.OnInitialized();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public XpoAgentTerrainSyncTable XpoAgentTerrain {
            get {
                return this._xpoAgentTerrainSyncTable;
            }
            set {
                this.Configuration.SyncTables.Remove(this._xpoAgentTerrainSyncTable);
                this._xpoAgentTerrainSyncTable = value;
                this.Configuration.SyncTables.Add(this._xpoAgentTerrainSyncTable);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public XpoCategorySyncTable XpoCategory {
            get {
                return this._xpoCategorySyncTable;
            }
            set {
                this.Configuration.SyncTables.Remove(this._xpoCategorySyncTable);
                this._xpoCategorySyncTable = value;
                this.Configuration.SyncTables.Add(this._xpoCategorySyncTable);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public XpoClientSyncTable XpoClient {
            get {
                return this._xpoClientSyncTable;
            }
            set {
                this.Configuration.SyncTables.Remove(this._xpoClientSyncTable);
                this._xpoClientSyncTable = value;
                this.Configuration.SyncTables.Add(this._xpoClientSyncTable);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public XpoMarqueSyncTable XpoMarque {
            get {
                return this._xpoMarqueSyncTable;
            }
            set {
                this.Configuration.SyncTables.Remove(this._xpoMarqueSyncTable);
                this._xpoMarqueSyncTable = value;
                this.Configuration.SyncTables.Add(this._xpoMarqueSyncTable);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public XpoOrderSyncTable XpoOrder {
            get {
                return this._xpoOrderSyncTable;
            }
            set {
                this.Configuration.SyncTables.Remove(this._xpoOrderSyncTable);
                this._xpoOrderSyncTable = value;
                this.Configuration.SyncTables.Add(this._xpoOrderSyncTable);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public XpoOrderLineSyncTable XpoOrderLine {
            get {
                return this._xpoOrderLineSyncTable;
            }
            set {
                this.Configuration.SyncTables.Remove(this._xpoOrderLineSyncTable);
                this._xpoOrderLineSyncTable = value;
                this.Configuration.SyncTables.Add(this._xpoOrderLineSyncTable);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public XpoProductSyncTable XpoProduct {
            get {
                return this._xpoProductSyncTable;
            }
            set {
                this.Configuration.SyncTables.Remove(this._xpoProductSyncTable);
                this._xpoProductSyncTable = value;
                this.Configuration.SyncTables.Add(this._xpoProductSyncTable);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public XpoProductLineSyncTable XpoProductLine {
            get {
                return this._xpoProductLineSyncTable;
            }
            set {
                this.Configuration.SyncTables.Remove(this._xpoProductLineSyncTable);
                this._xpoProductLineSyncTable = value;
                this.Configuration.SyncTables.Add(this._xpoProductLineSyncTable);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public XpoSectorSyncTable XpoSector {
            get {
                return this._xpoSectorSyncTable;
            }
            set {
                this.Configuration.SyncTables.Remove(this._xpoSectorSyncTable);
                this._xpoSectorSyncTable = value;
                this.Configuration.SyncTables.Add(this._xpoSectorSyncTable);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public XpoStockSyncTable XpoStock {
            get {
                return this._xpoStockSyncTable;
            }
            set {
                this.Configuration.SyncTables.Remove(this._xpoStockSyncTable);
                this._xpoStockSyncTable = value;
                this.Configuration.SyncTables.Add(this._xpoStockSyncTable);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitializeSyncProviders() {
            // Create SyncProviders.
            this.LocalProvider = new VenteEmbarqueCacheClientSyncProvider();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitializeSyncTables() {
            // Create SyncTables.
            this._xpoAgentTerrainSyncTable = new XpoAgentTerrainSyncTable();
            this._xpoAgentTerrainSyncTable.SyncGroup = new Microsoft.Synchronization.Data.SyncGroup("XpoAgentTerrainSyncTableSyncGroup");
            this.Configuration.SyncTables.Add(this._xpoAgentTerrainSyncTable);
            this._xpoCategorySyncTable = new XpoCategorySyncTable();
            this._xpoCategorySyncTable.SyncGroup = new Microsoft.Synchronization.Data.SyncGroup("XpoCategorySyncTableSyncGroup");
            this.Configuration.SyncTables.Add(this._xpoCategorySyncTable);
            this._xpoClientSyncTable = new XpoClientSyncTable();
            this._xpoClientSyncTable.SyncGroup = new Microsoft.Synchronization.Data.SyncGroup("XpoClientSyncTableSyncGroup");
            this.Configuration.SyncTables.Add(this._xpoClientSyncTable);
            this._xpoMarqueSyncTable = new XpoMarqueSyncTable();
            this._xpoMarqueSyncTable.SyncGroup = new Microsoft.Synchronization.Data.SyncGroup("XpoMarqueSyncTableSyncGroup");
            this.Configuration.SyncTables.Add(this._xpoMarqueSyncTable);
            this._xpoOrderSyncTable = new XpoOrderSyncTable();
            this._xpoOrderSyncTable.SyncGroup = new Microsoft.Synchronization.Data.SyncGroup("XpoOrderSyncTableSyncGroup");
            this.Configuration.SyncTables.Add(this._xpoOrderSyncTable);
            this._xpoOrderLineSyncTable = new XpoOrderLineSyncTable();
            this._xpoOrderLineSyncTable.SyncGroup = new Microsoft.Synchronization.Data.SyncGroup("XpoOrderLineSyncTableSyncGroup");
            this.Configuration.SyncTables.Add(this._xpoOrderLineSyncTable);
            this._xpoProductSyncTable = new XpoProductSyncTable();
            this._xpoProductSyncTable.SyncGroup = new Microsoft.Synchronization.Data.SyncGroup("XpoProductSyncTableSyncGroup");
            this.Configuration.SyncTables.Add(this._xpoProductSyncTable);
            this._xpoProductLineSyncTable = new XpoProductLineSyncTable();
            this._xpoProductLineSyncTable.SyncGroup = new Microsoft.Synchronization.Data.SyncGroup("XpoProductLineSyncTableSyncGroup");
            this.Configuration.SyncTables.Add(this._xpoProductLineSyncTable);
            this._xpoSectorSyncTable = new XpoSectorSyncTable();
            this._xpoSectorSyncTable.SyncGroup = new Microsoft.Synchronization.Data.SyncGroup("XpoSectorSyncTableSyncGroup");
            this.Configuration.SyncTables.Add(this._xpoSectorSyncTable);
            this._xpoStockSyncTable = new XpoStockSyncTable();
            this._xpoStockSyncTable.SyncGroup = new Microsoft.Synchronization.Data.SyncGroup("XpoStockSyncTableSyncGroup");
            this.Configuration.SyncTables.Add(this._xpoStockSyncTable);
        }
        
        public partial class XpoAgentTerrainSyncTable : Microsoft.Synchronization.Data.SyncTable {
            
            partial void OnInitialized();
            
            public XpoAgentTerrainSyncTable() {
                this.InitializeTableOptions();
                this.OnInitialized();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitializeTableOptions() {
                this.TableName = "XpoAgentTerrain";
                this.CreationOption = Microsoft.Synchronization.Data.TableCreationOption.DropExistingOrCreateNewTable;
            }
        }
        
        public partial class XpoCategorySyncTable : Microsoft.Synchronization.Data.SyncTable {
            
            partial void OnInitialized();
            
            public XpoCategorySyncTable() {
                this.InitializeTableOptions();
                this.OnInitialized();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitializeTableOptions() {
                this.TableName = "XpoCategory";
                this.CreationOption = Microsoft.Synchronization.Data.TableCreationOption.DropExistingOrCreateNewTable;
            }
        }
        
        public partial class XpoClientSyncTable : Microsoft.Synchronization.Data.SyncTable {
            
            partial void OnInitialized();
            
            public XpoClientSyncTable() {
                this.InitializeTableOptions();
                this.OnInitialized();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitializeTableOptions() {
                this.TableName = "XpoClient";
                this.CreationOption = Microsoft.Synchronization.Data.TableCreationOption.DropExistingOrCreateNewTable;
            }
        }
        
        public partial class XpoMarqueSyncTable : Microsoft.Synchronization.Data.SyncTable {
            
            partial void OnInitialized();
            
            public XpoMarqueSyncTable() {
                this.InitializeTableOptions();
                this.OnInitialized();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitializeTableOptions() {
                this.TableName = "XpoMarque";
                this.CreationOption = Microsoft.Synchronization.Data.TableCreationOption.DropExistingOrCreateNewTable;
            }
        }
        
        public partial class XpoOrderSyncTable : Microsoft.Synchronization.Data.SyncTable {
            
            partial void OnInitialized();
            
            public XpoOrderSyncTable() {
                this.InitializeTableOptions();
                this.OnInitialized();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitializeTableOptions() {
                this.TableName = "XpoOrder";
                this.CreationOption = Microsoft.Synchronization.Data.TableCreationOption.DropExistingOrCreateNewTable;
            }
        }
        
        public partial class XpoOrderLineSyncTable : Microsoft.Synchronization.Data.SyncTable {
            
            partial void OnInitialized();
            
            public XpoOrderLineSyncTable() {
                this.InitializeTableOptions();
                this.OnInitialized();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitializeTableOptions() {
                this.TableName = "XpoOrderLine";
                this.CreationOption = Microsoft.Synchronization.Data.TableCreationOption.DropExistingOrCreateNewTable;
            }
        }
        
        public partial class XpoProductSyncTable : Microsoft.Synchronization.Data.SyncTable {
            
            partial void OnInitialized();
            
            public XpoProductSyncTable() {
                this.InitializeTableOptions();
                this.OnInitialized();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitializeTableOptions() {
                this.TableName = "XpoProduct";
                this.CreationOption = Microsoft.Synchronization.Data.TableCreationOption.DropExistingOrCreateNewTable;
            }
        }
        
        public partial class XpoProductLineSyncTable : Microsoft.Synchronization.Data.SyncTable {
            
            partial void OnInitialized();
            
            public XpoProductLineSyncTable() {
                this.InitializeTableOptions();
                this.OnInitialized();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitializeTableOptions() {
                this.TableName = "XpoProductLine";
                this.CreationOption = Microsoft.Synchronization.Data.TableCreationOption.DropExistingOrCreateNewTable;
            }
        }
        
        public partial class XpoSectorSyncTable : Microsoft.Synchronization.Data.SyncTable {
            
            partial void OnInitialized();
            
            public XpoSectorSyncTable() {
                this.InitializeTableOptions();
                this.OnInitialized();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitializeTableOptions() {
                this.TableName = "XpoSector";
                this.CreationOption = Microsoft.Synchronization.Data.TableCreationOption.DropExistingOrCreateNewTable;
            }
        }
        
        public partial class XpoStockSyncTable : Microsoft.Synchronization.Data.SyncTable {
            
            partial void OnInitialized();
            
            public XpoStockSyncTable() {
                this.InitializeTableOptions();
                this.OnInitialized();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitializeTableOptions() {
                this.TableName = "XpoStock";
                this.CreationOption = Microsoft.Synchronization.Data.TableCreationOption.DropExistingOrCreateNewTable;
            }
        }
    }
}
